data:
  name: Burgers
  datapath: '/home/tp526/neuraloperator/data/burgers_pino_x80_t81.mat'
  total_num: 1000
  offset: 0
  n_sample: 800
  nx: 80
  nt: 80
  sub: 1
  sub_t: 1 

model:
  layers: [64, 64, 64, 64, 64] #[16, 24, 24, 32, 32]
  modes1: [15, 12, 9, 9]
  modes2: [15, 12, 9, 9]
  fc_dim: 128
  act: gelu
  num_pad: 4

train:
  batchsize: 32
  epochs: 500
  milestones: [100, 200, 300, 400]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.001
  xy_loss: 1.0
  save_dir: 'burgers-FDM'
  save_name: 'burgers-invisicd-data-0-pde-0.01-5-64-mode-15-x80.pt'

log:
  project: PINO-burgers-pretrain
  group: gelu-eqn
  entity: hzzheng-pino

